# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kadurugved0@gmail.com
author_name: John Doe
contract_name: defi_exchange
deployment_language: python
preset_name: starter
project_name: defi_exchange

